import type { Template, TemplateCategory } from './types';

// Restaurant Templates (6)
const restaurantTemplates: Template[] = [
  {
    id: 'restaurant-modern-menu',
    name: 'Modern Menu',
    description: 'Sleek dark theme with cyan gradient for upscale dining',
    category: 'restaurant',
    qrType: 'menu',
    tags: ['menu', 'dining', 'modern', 'upscale'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#0891b2',
      backgroundColor: '#0f172a',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#0891b2',
        endColor: '#06b6d4',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 20,
        color: '#0891b2',
        radius: '12%',
        text: { bottom: 'VIEW MENU' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'restaurant-cafe',
    name: 'Cafe Classic',
    description: 'Warm brown tones on cream background for coffee shops',
    category: 'restaurant',
    qrType: 'menu',
    tags: ['cafe', 'coffee', 'warm', 'classic'],
    tier: 'free',
    style: {
      foregroundColor: '#3d2314',
      backgroundColor: '#fef3c7',
    },
  },
  {
    id: 'restaurant-food-truck',
    name: 'Food Truck',
    description: 'Vibrant orange gradient for casual street food',
    category: 'restaurant',
    qrType: 'menu',
    tags: ['food truck', 'casual', 'street food', 'vibrant'],
    tier: 'pro',
    style: {
      foregroundColor: '#ea580c',
      backgroundColor: '#ffffff',
      moduleShape: 'extraRounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#f97316',
        endColor: '#ea580c',
        angle: 180,
      },
      frame: {
        enabled: true,
        thickness: 24,
        color: '#ea580c',
        radius: '16%',
        text: { bottom: 'ORDER NOW' },
        textStyle: { fontColor: '#ffffff', fontSize: 16 },
      },
    },
  },
  {
    id: 'restaurant-fine-dining',
    name: 'Fine Dining',
    description: 'Elegant black and white with gold accents',
    category: 'restaurant',
    qrType: 'menu',
    tags: ['fine dining', 'elegant', 'luxury', 'upscale'],
    tier: 'pro',
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
      moduleShape: 'classy',
      frame: {
        enabled: true,
        thickness: 12,
        color: '#d4af37',
        radius: '0%',
        text: { bottom: 'MENU' },
        textStyle: { fontColor: '#d4af37', fontSize: 12 },
      },
    },
  },
  {
    id: 'restaurant-reviews',
    name: 'Review Request',
    description: 'Fresh green design to encourage Google reviews',
    category: 'restaurant',
    qrType: 'google-review',
    tags: ['reviews', 'google', 'feedback', 'rating'],
    tier: 'free',
    style: {
      foregroundColor: '#16a34a',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'restaurant-wifi',
    name: 'Guest WiFi',
    description: 'Teal gradient with WiFi frame text',
    category: 'restaurant',
    qrType: 'wifi',
    tags: ['wifi', 'guest', 'network', 'internet'],
    tier: 'pro',
    style: {
      foregroundColor: '#0d9488',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#14b8a6',
        endColor: '#0d9488',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 20,
        color: '#0d9488',
        radius: '12%',
        text: { bottom: 'FREE WIFI' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
];

// Business Templates (6)
const businessTemplates: Template[] = [
  {
    id: 'business-executive',
    name: 'Executive Card',
    description: 'Professional black and white for corporate contacts',
    category: 'business',
    qrType: 'vcard',
    tags: ['executive', 'corporate', 'professional', 'contact'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
      moduleShape: 'classy',
      frame: {
        enabled: true,
        thickness: 16,
        color: '#6b7280',
        radius: '8%',
        text: { bottom: 'CONTACT' },
        textStyle: { fontColor: '#374151', fontSize: 12 },
      },
    },
  },
  {
    id: 'business-startup',
    name: 'Startup Modern',
    description: 'Electric blue to purple gradient for tech companies',
    category: 'business',
    qrType: 'vcard',
    tags: ['startup', 'tech', 'modern', 'gradient'],
    tier: 'pro',
    style: {
      foregroundColor: '#3b82f6',
      backgroundColor: '#ffffff',
      moduleShape: 'dots',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#3b82f6',
        endColor: '#8b5cf6',
        angle: 135,
      },
    },
  },
  {
    id: 'business-consultant',
    name: 'Consultant',
    description: 'Classic navy on white for professional services',
    category: 'business',
    qrType: 'vcard',
    tags: ['consultant', 'professional', 'classic', 'navy'],
    tier: 'free',
    style: {
      foregroundColor: '#1e3a5f',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'business-creative',
    name: 'Creative Pro',
    description: 'Vibrant gradient for creative agencies and studios',
    category: 'business',
    qrType: 'business',
    tags: ['creative', 'agency', 'colorful', 'modern'],
    tier: 'pro',
    style: {
      foregroundColor: '#ec4899',
      backgroundColor: '#ffffff',
      moduleShape: 'extraRounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#ec4899',
        endColor: '#8b5cf6',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 20,
        color: '#ec4899',
        radius: '16%',
        text: { bottom: 'CONNECT' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'business-minimal',
    name: 'Minimal Contact',
    description: 'Clean and simple for minimalist brands',
    category: 'business',
    qrType: 'vcard',
    tags: ['minimal', 'simple', 'clean', 'modern'],
    tier: 'free',
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'business-linkedin',
    name: 'LinkedIn Connect',
    description: 'LinkedIn blue with professional styling',
    category: 'business',
    qrType: 'linkedin',
    tags: ['linkedin', 'networking', 'professional', 'social'],
    tier: 'pro',
    style: {
      foregroundColor: '#0077b5',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#0077b5',
        radius: '10%',
        text: { bottom: 'CONNECT' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
];

// Marketing Templates (7)
const marketingTemplates: Template[] = [
  {
    id: 'marketing-product-launch',
    name: 'Product Launch',
    description: 'Bold orange for product announcements',
    category: 'marketing',
    qrType: 'url',
    tags: ['product', 'launch', 'announcement', 'bold'],
    tier: 'free',
    featured: true,
    style: {
      foregroundColor: '#ea580c',
      backgroundColor: '#ffffff',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#ea580c',
        radius: '10%',
        text: { bottom: 'LEARN MORE' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'marketing-sale-promo',
    name: 'Sale Promo',
    description: 'Red gradient for sales and promotions',
    category: 'marketing',
    qrType: 'url',
    tags: ['sale', 'promotion', 'discount', 'red'],
    tier: 'pro',
    style: {
      foregroundColor: '#dc2626',
      backgroundColor: '#ffffff',
      moduleShape: 'extraRounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#ef4444',
        endColor: '#dc2626',
        angle: 180,
      },
      frame: {
        enabled: true,
        thickness: 22,
        color: '#dc2626',
        radius: '14%',
        text: { bottom: 'SHOP NOW' },
        textStyle: { fontColor: '#ffffff', fontSize: 16 },
      },
    },
  },
  {
    id: 'marketing-lead-gen',
    name: 'Lead Generator',
    description: 'Teal on dark for lead capture landing pages',
    category: 'marketing',
    qrType: 'url',
    tags: ['leads', 'signup', 'conversion', 'teal'],
    tier: 'pro',
    style: {
      foregroundColor: '#14b8a6',
      backgroundColor: '#1e293b',
      moduleShape: 'rounded',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#14b8a6',
        radius: '12%',
        text: { bottom: 'SIGN UP' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'marketing-app-download',
    name: 'App Download',
    description: 'Purple gradient for mobile app promotions',
    category: 'marketing',
    qrType: 'apps',
    tags: ['app', 'download', 'mobile', 'purple'],
    tier: 'pro',
    style: {
      foregroundColor: '#7c3aed',
      backgroundColor: '#ffffff',
      moduleShape: 'dots',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#8b5cf6',
        endColor: '#7c3aed',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 20,
        color: '#7c3aed',
        radius: '14%',
        text: { bottom: 'GET THE APP' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'marketing-feedback',
    name: 'Customer Feedback',
    description: 'Friendly green for feedback collection',
    category: 'marketing',
    qrType: 'url',
    tags: ['feedback', 'survey', 'customer', 'green'],
    tier: 'free',
    style: {
      foregroundColor: '#16a34a',
      backgroundColor: '#ffffff',
      frame: {
        enabled: true,
        thickness: 16,
        color: '#16a34a',
        radius: '10%',
        text: { bottom: 'SHARE FEEDBACK' },
        textStyle: { fontColor: '#ffffff', fontSize: 12 },
      },
    },
  },
  {
    id: 'marketing-coupon',
    name: 'Discount Code',
    description: 'Gold gradient for special offers and coupons',
    category: 'marketing',
    qrType: 'coupon',
    tags: ['coupon', 'discount', 'offer', 'gold'],
    tier: 'pro',
    style: {
      foregroundColor: '#f59e0b',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#fbbf24',
        endColor: '#f59e0b',
        angle: 180,
      },
      frame: {
        enabled: true,
        thickness: 22,
        color: '#f59e0b',
        radius: '12%',
        text: { bottom: 'SAVE NOW' },
        textStyle: { fontColor: '#ffffff', fontSize: 16 },
      },
    },
  },
  {
    id: 'marketing-video',
    name: 'Video Content',
    description: 'YouTube red for video marketing',
    category: 'marketing',
    qrType: 'youtube',
    tags: ['video', 'youtube', 'content', 'media'],
    tier: 'pro',
    style: {
      foregroundColor: '#ff0000',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
    },
  },
];

// Events Templates (5)
const eventsTemplates: Template[] = [
  {
    id: 'events-conference',
    name: 'Conference Badge',
    description: 'Professional blue gradient for corporate events',
    category: 'events',
    qrType: 'event',
    tags: ['conference', 'corporate', 'badge', 'professional'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#2563eb',
      backgroundColor: '#ffffff',
      moduleShape: 'classy',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#3b82f6',
        endColor: '#2563eb',
        angle: 180,
      },
      frame: {
        enabled: true,
        thickness: 18,
        color: '#2563eb',
        radius: '10%',
        text: { bottom: 'REGISTER' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'events-wedding',
    name: 'Wedding RSVP',
    description: 'Elegant rose gold for wedding invitations',
    category: 'events',
    qrType: 'event',
    tags: ['wedding', 'rsvp', 'elegant', 'romantic'],
    tier: 'pro',
    style: {
      foregroundColor: '#b76e79',
      backgroundColor: '#ffffff',
      moduleShape: 'classyRounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#d4a5a5',
        endColor: '#b76e79',
        angle: 135,
      },
    },
  },
  {
    id: 'events-concert',
    name: 'Concert Ticket',
    description: 'Bold purple on black for music events',
    category: 'events',
    qrType: 'event',
    tags: ['concert', 'music', 'ticket', 'entertainment'],
    tier: 'free',
    style: {
      foregroundColor: '#7c3aed',
      backgroundColor: '#0f0f0f',
      moduleShape: 'dots',
    },
  },
  {
    id: 'events-registration',
    name: 'Event Check-in',
    description: 'Clean teal for event registration',
    category: 'events',
    qrType: 'url',
    tags: ['registration', 'check-in', 'event', 'teal'],
    tier: 'free',
    style: {
      foregroundColor: '#0d9488',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'events-schedule',
    name: 'Event Schedule',
    description: 'Dark theme with cyan accent for schedules',
    category: 'events',
    qrType: 'url',
    tags: ['schedule', 'agenda', 'event', 'dark'],
    tier: 'pro',
    style: {
      foregroundColor: '#06b6d4',
      backgroundColor: '#1e293b',
      moduleShape: 'rounded',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#06b6d4',
        radius: '12%',
        text: { bottom: 'VIEW SCHEDULE' },
        textStyle: { fontColor: '#ffffff', fontSize: 12 },
      },
    },
  },
];

// Social Templates (6)
const socialTemplates: Template[] = [
  {
    id: 'social-instagram',
    name: 'Instagram Profile',
    description: 'Instagram gradient colors for profile links',
    category: 'social',
    qrType: 'instagram',
    tags: ['instagram', 'social', 'profile', 'gradient'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#e6683c',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#f09433',
        endColor: '#bc1888',
        angle: 135,
      },
    },
  },
  {
    id: 'social-tiktok',
    name: 'TikTok Follow',
    description: 'TikTok cyan and magenta for profiles',
    category: 'social',
    qrType: 'tiktok',
    tags: ['tiktok', 'social', 'video', 'trending'],
    tier: 'pro',
    style: {
      foregroundColor: '#00f2ea',
      backgroundColor: '#000000',
      moduleShape: 'dots',
    },
  },
  {
    id: 'social-linktree',
    name: 'Link Tree',
    description: 'Green gradient for link-in-bio pages',
    category: 'social',
    qrType: 'links',
    tags: ['links', 'linktree', 'bio', 'green'],
    tier: 'pro',
    style: {
      foregroundColor: '#22c55e',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#22c55e',
        endColor: '#14b8a6',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 18,
        color: '#22c55e',
        radius: '12%',
        text: { bottom: 'MY LINKS' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'social-youtube',
    name: 'YouTube Channel',
    description: 'Classic YouTube red for channel promotion',
    category: 'social',
    qrType: 'youtube',
    tags: ['youtube', 'video', 'channel', 'red'],
    tier: 'free',
    style: {
      foregroundColor: '#ff0000',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'social-twitter',
    name: 'X Profile',
    description: 'Clean black and white for X/Twitter',
    category: 'social',
    qrType: 'x',
    tags: ['twitter', 'x', 'social', 'minimal'],
    tier: 'free',
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'social-all-platforms',
    name: 'Social Hub',
    description: 'Rainbow gradient for multi-platform profiles',
    category: 'social',
    qrType: 'social',
    tags: ['social', 'hub', 'all', 'rainbow'],
    tier: 'pro',
    style: {
      foregroundColor: '#8b5cf6',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#ec4899',
        endColor: '#8b5cf6',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 18,
        color: '#8b5cf6',
        radius: '12%',
        text: { bottom: 'FOLLOW ME' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
];

// Retail Templates (6)
const retailTemplates: Template[] = [
  {
    id: 'retail-product-info',
    name: 'Product Info',
    description: 'Clean black for product information displays',
    category: 'retail',
    qrType: 'url',
    tags: ['product', 'info', 'retail', 'clean'],
    tier: 'free',
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
      frame: {
        enabled: true,
        thickness: 16,
        color: '#374151',
        radius: '8%',
        text: { bottom: 'PRODUCT DETAILS' },
        textStyle: { fontColor: '#ffffff', fontSize: 11 },
      },
    },
  },
  {
    id: 'retail-price-check',
    name: 'Price Check',
    description: 'Green for in-store price checking',
    category: 'retail',
    qrType: 'url',
    tags: ['price', 'check', 'store', 'green'],
    tier: 'pro',
    style: {
      foregroundColor: '#16a34a',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#16a34a',
        radius: '10%',
        text: { bottom: 'CHECK PRICE' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'retail-loyalty',
    name: 'Loyalty Program',
    description: 'Premium gold gradient for rewards programs',
    category: 'retail',
    qrType: 'url',
    tags: ['loyalty', 'rewards', 'program', 'gold'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#d97706',
      backgroundColor: '#ffffff',
      moduleShape: 'classy',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#fbbf24',
        endColor: '#d97706',
        angle: 180,
      },
      frame: {
        enabled: true,
        thickness: 20,
        color: '#d97706',
        radius: '12%',
        text: { bottom: 'JOIN REWARDS' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
  {
    id: 'retail-warranty',
    name: 'Warranty Registration',
    description: 'Professional navy for warranty cards',
    category: 'retail',
    qrType: 'url',
    tags: ['warranty', 'registration', 'product', 'navy'],
    tier: 'free',
    style: {
      foregroundColor: '#1e3a5f',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'retail-reviews',
    name: 'Product Reviews',
    description: 'Star yellow accent for review requests',
    category: 'retail',
    qrType: 'google-review',
    tags: ['reviews', 'rating', 'product', 'yellow'],
    tier: 'pro',
    style: {
      foregroundColor: '#ca8a04',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      frame: {
        enabled: true,
        thickness: 18,
        color: '#fbbf24',
        radius: '10%',
        text: { bottom: 'RATE US' },
        textStyle: { fontColor: '#000000', fontSize: 14 },
      },
    },
  },
  {
    id: 'retail-reorder',
    name: 'Easy Reorder',
    description: 'Teal gradient for repeat purchase QR codes',
    category: 'retail',
    qrType: 'url',
    tags: ['reorder', 'repeat', 'purchase', 'teal'],
    tier: 'pro',
    style: {
      foregroundColor: '#0d9488',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#14b8a6',
        endColor: '#0d9488',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 18,
        color: '#0d9488',
        radius: '12%',
        text: { bottom: 'REORDER NOW' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
];

// Creative Templates (4)
const creativeTemplates: Template[] = [
  {
    id: 'creative-portfolio',
    name: 'Portfolio',
    description: 'Artistic gradient for creative portfolios',
    category: 'creative',
    qrType: 'url',
    tags: ['portfolio', 'creative', 'artist', 'gradient'],
    tier: 'pro',
    featured: true,
    style: {
      foregroundColor: '#8b5cf6',
      backgroundColor: '#ffffff',
      moduleShape: 'extraRounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#ec4899',
        endColor: '#8b5cf6',
        angle: 135,
      },
    },
  },
  {
    id: 'creative-artist',
    name: 'Artist Profile',
    description: 'Clean black and white for artists',
    category: 'creative',
    qrType: 'instagram',
    tags: ['artist', 'gallery', 'minimal', 'clean'],
    tier: 'free',
    style: {
      foregroundColor: '#000000',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'creative-photographer',
    name: 'Photography',
    description: 'Monochrome gradient for photographers',
    category: 'creative',
    qrType: 'url',
    tags: ['photography', 'photo', 'monochrome', 'elegant'],
    tier: 'pro',
    style: {
      foregroundColor: '#374151',
      backgroundColor: '#ffffff',
      moduleShape: 'classy',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#6b7280',
        endColor: '#374151',
        angle: 180,
      },
    },
  },
  {
    id: 'creative-studio',
    name: 'Design Studio',
    description: 'Vibrant multi-color for design agencies',
    category: 'creative',
    qrType: 'business',
    tags: ['design', 'studio', 'agency', 'vibrant'],
    tier: 'pro',
    style: {
      foregroundColor: '#f97316',
      backgroundColor: '#ffffff',
      moduleShape: 'rounded',
      gradient: {
        enabled: true,
        type: 'linear',
        startColor: '#f97316',
        endColor: '#ec4899',
        angle: 135,
      },
      frame: {
        enabled: true,
        thickness: 18,
        color: '#f97316',
        radius: '12%',
        text: { bottom: 'VISIT STUDIO' },
        textStyle: { fontColor: '#ffffff', fontSize: 14 },
      },
    },
  },
];

// Combine all templates
export const TEMPLATES: Template[] = [
  ...restaurantTemplates,
  ...businessTemplates,
  ...marketingTemplates,
  ...eventsTemplates,
  ...socialTemplates,
  ...retailTemplates,
  ...creativeTemplates,
];

// Get template by ID
export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

// Get templates by category
export function getTemplatesByCategory(category: TemplateCategory): Template[] {
  return TEMPLATES.filter((t) => t.category === category);
}

// Get featured templates
export function getFeaturedTemplates(): Template[] {
  return TEMPLATES.filter((t) => t.featured);
}

// Get free templates
export function getFreeTemplates(): Template[] {
  return TEMPLATES.filter((t) => t.tier === 'free');
}

// Search templates
export function searchTemplates(query: string): Template[] {
  const lowerQuery = query.toLowerCase();
  return TEMPLATES.filter(
    (t) =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}
